### PR TITLE
Changes to adapt to new stuff in database/sql

### PR DESCRIPTION
**Pull request by mikelikespie**

### CODE REVIEW

**Comment by irrelative** [comment]
Nice, thanks mikelikespie. I had to add the import "database/sql/driver" to proto/proto.go to make this build though.

**Comment by mikelikespie** [comment]
It is really hard to test changes to the proto stuff because the imports reference the github.com project.  Is there something I am missing with the new go tool stuff?

**Comment by bmizerany** [comment]
Awesome. I'm in the middle of a rewrite. This will be fixed in 2.0. There a number of problems with the current design.

If you don't mind using you're own for now. This will keep from breaking current apps. I may make the new codebase a new project.

**Comment by bmizerany** [comment]
This is fixed in the over branch which will be master soon.

**Pull request closed without merging**
